src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

     /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    
}



    

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gablau Services
{% endblock %}

{% block body %}
	{% if app.user %}
		<div class="mb-3">
			You are logged in as
			{{ app.user.prenom }},
			<a href="{{ path('app_logout') }}">Logout</a>
		</div>
	{% endif %}

	<section id="hero">
		<div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

			<ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

			<div
				class="carousel-inner" role="listbox">
				<!-- Slide 1 -->
				<div class="carousel-item active" style="background-image: url(assets/img/slide/slide-1.jpg)">
					<div class="carousel-container">
						<div class="container">
							<h2 class="animate__animated animate__fadeInDown">Bienvenu à
								<span>Gablau Services</span>
							</h2>
							<p class="animate__animated animate__fadeInUp">Vitrine virtuelle à travers laquelle le client peut consulter une grande variétés des produits.</p>
							<a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Détails....</a>
						</div>
					</div>
				</div>

				<!-- Slide 2 -->
				<div class="carousel-item" style="background-image: url(assets/img/slide/slide-2.jpg)">
					<div class="carousel-container">
						<div class="container">
							<h2 class="animate__animated animate__fadeInDown">Gablau Services G&S</h2>
							<p class="animate__animated animate__fadeInUp">Découvrez les équipements électroniques de toutes marques sur cette plateforme de commerce.</p>
							<a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Détails...</a>
						</div>
					</div>
				</div>

				<!-- Slide 3 -->
				<div class="carousel-item" style="background-image: url(assets/img/slide/slide-3.jpg)">
					<div class="carousel-container">
						<div class="container">
							<h2 class="animate__animated animate__fadeInDown">Gablau Services G&S</h2>
							<p class="animate__animated animate__fadeInUp">Découvrez également nos services qui vous sont offerts.</p>
							<a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Détails...</a>
						</div>
					</div>
				</div>


			</div>
		</section>
		<!-- End Hero -->

	</div>


	<!-- ======= Portfolio Section ======= -->
	<section id="portfolio" class="portfolio">
		<div class="container">

			<div class="row">
				<div class="col-lg-12 d-flex justify-content-center">
					<ul id="portfolio-flters">
						<li data-filter="*" class="filter-active">All</li>
						<li data-filter=".filter-app">Informatique</li>
						<li data-filter=".filter-card">Electroménager</li>
						<li data-filter=".filter-web">Electronique</li>

					</ul>
				</div>
			</div>
			<div class="row portfolio-container">

				<div class="col-lg-4 col-md-6 portfolio-item filter-app">
					<div class="portfolio-wrap">
						<img src="{{ asset('assets/img/portfolio/laptop1.jpg')}}" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Informatique 1</h4>
							<p>Informatique</p>
							<div class="portfolio-links">
								<a href="{{asset('assets/img/portfolio/laptop1.jpg')}}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 portfolio-item filter-web">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/smart3.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Electronique 3</h4>
							<p>Electronique</p>
							<div class="portfolio-links">
								<a href="{{asset('assets/img/portfolio/smart3.jpe')}}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 3">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 portfolio-item filter-app">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/ordi5.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Informatique 2</h4>
							<p>Informatique</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/ordi5.jpe" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 2">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 portfolio-item filter-card">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/electro3.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Electroménager 2</h4>
							<p>Electroménager</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/electro3.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Card 2">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 portfolio-item filter-web">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/Smart1.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Electronique 2</h4>
							<p>Electronique</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/Smart1.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 2">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 portfolio-item filter-app">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/ordi1.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Informatique 3</h4>
							<p>Informatique</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/ordi1.jpe" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 3">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 portfolio-item filter-card">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/electro2.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Elecrtoménager 1</h4>
							<p>Electroménager</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/electro2.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Card 1">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 portfolio-item filter-card">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/electro1.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Electroménager 3</h4>
							<p>Electroménager</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/electro1.jpe" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Card 3">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 portfolio-item filter-web">
					<div class="portfolio-wrap">
						<img src="assets/img/portfolio/smart4.jpe" class="img-fluid" alt="">
						<div class="portfolio-info">
							<h4>Electronique 3</h4>
							<p>Electronique</p>
							<div class="portfolio-links">
								<a href="assets/img/portfolio/smart4.jpe" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 3">
									<i class="bx bx-plus"></i>
								</a>
								<a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details">
									<i class="bx bx-link"></i>
								</a>
							</div>
						</div>
					</div>
				</div>

			</div>

		</div>
	</section>
	<!-- End Portfolio Section -->

</main>
<!-- End #main -->

<div class="text-center mb-3">
	<a class="btn btn-primary" href="{{ path('user') }}">Voir mon profil</a>
</div>{% endblock %}